import createAcc from "../../pageObject/create.acc"
const userData = require('../../fixtures/user_data.json')  

describe('Verify Create an Account Functionality', () => {
  
    beforeEach(() => {
      cy.visit('')
    })
    it('Success Create an Account', () => {
      cy.create()
      cy.get(createAcc.fname).type(userData.validUser.firstName)
      cy.get(createAcc.lname).type(userData.validUser.lastName)
      cy.get(createAcc.email).type(userData.validUser.email)
      cy.get(createAcc.pass).type(userData.validUser.password)
      cy.get(createAcc.confirm).type(userData.validUser.confirmPass)
      cy.createBtn()
      cy.get('.message-success > div').should('be.visible')
    })
    it('Failed - Email Already Registered', () => {
      cy.create()
      cy.get(createAcc.fname).type(userData.validUser.firstName)
      cy.get(createAcc.lname).type(userData.validUser.lastName)
      cy.get(createAcc.email).type(userData.validUser.email)
      cy.get(createAcc.pass).type(userData.validUser.password)
      cy.get(createAcc.confirm).type(userData.validUser.confirmPass)
      cy.createBtn()
      cy.get('.message-error > div').should('be.visible')
    })
    it('Failed - Name Field Empty', () => {
      cy.create()
      cy.get(createAcc.email).type(userData.validUser.email)
      cy.get(createAcc.pass).type(userData.validUser.password)
      cy.get(createAcc.confirm).type(userData.validUser.confirmPass)
      cy.createBtn()
      cy.get('#firstname-error').should('be.visible')
      cy.get('#lastname-error').should('be.visible')
    })
    it('Failed - Invalid Email', () => {
      cy.create()
      cy.get(createAcc.fname).type(userData.validUser.firstName)
      cy.get(createAcc.lname).type(userData.validUser.lastName)
      cy.get(createAcc.email).type(userData.invalidUser.email)
      cy.get(createAcc.pass).type(userData.validUser.password)
      cy.get(createAcc.confirm).type(userData.validUser.confirmPass)
      cy.createBtn()
      cy.get('#email_address-error').should('be.visible')
    })
    it('Failed - Weak Password', () => {
      cy.create()
      cy.get(createAcc.fname).type(userData.validUser.firstName)
      cy.get(createAcc.lname).type(userData.validUser.lastName)
      cy.get(createAcc.email).type(userData.validUser.email)
      cy.get(createAcc.pass).type(userData.invalidUser.password)
      cy.get(createAcc.confirm).type(userData.invalidUser.confirmPass)
      cy.createBtn()
      cy.get('#password-error').should('be.visible')
    })
    it('Failed - Wrong Confirm Password', () => {
      cy.create()
      cy.get(createAcc.fname).type(userData.validUser.firstName)
      cy.get(createAcc.lname).type(userData.validUser.lastName)
      cy.get(createAcc.email).type(userData.validUser.email)
      cy.get(createAcc.pass).type(userData.validUser.password)
      cy.get(createAcc.confirm).type(userData.invalidUser.confirmPass)
      cy.createBtn()
      cy.get('#password-confirmation-error').should('be.visible')
    })

  })